#cloud-config
autoinstall:
  version: 1
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: SITE-CCTV-SRV-#
    password: $6$6badMgZimsD.DcCl$k6nmNLVQSkEZLHvDoElHe7TFVY3NNJ7baHu0ncugYLxPfHEfOArQ6EiN1ah7G8GEijBer/.2SuO/z7ZUuiKhf1
    realname: localadmin
    username: localadmin
  interactive-sections:
    - identity
  keyboard:
    layout: au
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      eno1:
        dhcp4: true
    version: 2
  oem:
    install: auto
  packages:
    - nala
    - nano
    - haveged
    - curl
    - apt-transport-https
    - wget
    - screen
    - git
    - htop
    - cifs-utils
    - net-tools
    - zfsutils-linux
  source:
    id: ubuntu-desktop-minimal
    search_drivers: true
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    layout:
      name: lvm
      sizing-policy: all
      match:
        path: /dev/nvme*
  timezone: Australia/Brisbane
  updates: security
  
